 whatis("GCC Version 12 compiler")
 setenv("CC", "/usr/bin/gcc-12")
 setenv("CXX", "/usr/bin/g++-12")
 setenv("F77", "/usr/bin/gfortran-12")
 setenv("F90", "/usr/bin/gfortran-12")
 setenv("FC", "/usr/bin/gfortran-12")
 append_path("INCLUDE_PATH", "/usr/include")
 prepend_path("LIBRARY_PATH", "/usr/lib/gcc/x86_64-linux-gnu/12")
 prepend_path("LD_LIBRARY_PATH", "/usr/lib/gcc/x86_64-linux-gnu/12")
 load("rocm")
 family("compiler")
