 whatis("GCC Version 13 compiler")
 setenv("CC", "/usr/bin/gcc-13")
 setenv("CXX", "/usr/bin/g++-13")
 setenv("F77", "/usr/bin/gfortran-13")
 setenv("F90", "/usr/bin/gfortran-13")
 setenv("FC", "/usr/bin/gfortran-13")
 append_path("INCLUDE_PATH", "/usr/include")
 prepend_path("LIBRARY_PATH", "/usr/lib/gcc/x86_64-linux-gnu/13")
 prepend_path("LD_LIBRARY_PATH", "/usr/lib/gcc/x86_64-linux-gnu/13")
 load("rocm")
 family("compiler")
